version: '3.8'

services:
  tourist-service:
    build:
      context: .
      dockerfile: dockerfile     
    container_name: tourist-be
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - LOCATION_API_KEY=${LOCATION_API_KEY}
      - REDIS_ADDR=redis_cache:6379
    depends_on:
      - redis_cache

  redis_cache:
    image: redis:alpine
    container_name: redis_cache
    ports:
    - "6379:6379"
  
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword # BẮT BUỘC PHẢI CÓ DÒNG NÀY
      - POSTGRES_DB=tourist_db
    ports:
      - "5432:5432"